/**
 * A mapping of NCAA team names to their respective conferences.
 * This provides a comprehensive data source for conference filtering,
 * supplementing the ranked-teams data from Firestore.
 * Note: Team names from the Odds API can vary slightly. This map
 * attempts to cover common variations.
 */
export const ncaaConferenceMap: Record<string, string> = {
  // Big 10
  "Illinois Fighting Illini": "Big 10",
  "Illinois": "Big 10",
  "Indiana Hoosiers": "Big 10",
  "Indiana": "Big 10",
  "Iowa Hawkeyes": "Big 10",
  "Iowa": "Big 10",
  "Maryland Terrapins": "Big 10",
  "Maryland": "Big 10",
  "Michigan Wolverines": "Big 10",
  "Michigan": "Big 10",
  "Michigan State Spartans": "Big 10",
  "Michigan State": "Big 10",
  "Minnesota Golden Gophers": "Big 10",
  "Minnesota": "Big 10",
  "Nebraska Cornhuskers": "Big 10",
  "Nebraska": "Big 10",
  "Northwestern Wildcats": "Big 10",
  "Northwestern": "Big 10",
  "Ohio State Buckeyes": "Big 10",
  "Ohio State": "Big 10",
  "Penn State Nittany Lions": "Big 10",
  "Penn State": "Big 10",
  "Purdue Boilermakers": "Big 10",
  "Purdue": "Big 10",
  "Rutgers Scarlet Knights": "Big 10",
  "Rutgers": "Big 10",
  "Wisconsin Badgers": "Big 10",
  "Wisconsin": "Big 10",
  "Oregon Ducks": "Big 10",
  "Oregon": "Big 10",
  "UCLA Bruins": "Big 10",
  "UCLA": "Big 10",
  "USC Trojans": "Big 10",
  "USC": "Big 10",
  "Washington Huskies": "Big 10",
  "Washington": "Big 10",

  // SEC
  "Alabama Crimson Tide": "SEC",
  "Alabama": "SEC",
  "Arkansas Razorbacks": "SEC",
  "Arkansas": "SEC",
  "Auburn Tigers": "SEC",
  "Auburn": "SEC",
  "Florida Gators": "SEC",
  "Florida": "SEC",
  "Georgia Bulldogs": "SEC",
  "Georgia": "SEC",
  "Kentucky Wildcats": "SEC",
  "Kentucky": "SEC",
  "LSU Tigers": "SEC",
  "LSU": "SEC",
  "Mississippi State Bulldogs": "SEC",
  "Mississippi State": "SEC",
  "Missouri Tigers": "SEC",
  "Missouri": "SEC",
  "Ole Miss Rebels": "SEC",
  "Ole Miss": "SEC",
  "South Carolina Gamecocks": "SEC",
  "South Carolina": "SEC",
  "Tennessee Volunteers": "SEC",
  "Tennessee": "SEC",
  "Texas A&M Aggies": "SEC",
  "Texas A&M": "SEC",
  "Vanderbilt Commodores": "SEC",
  "Vanderbilt": "SEC",
  "Oklahoma Sooners": "SEC",
  "Oklahoma": "SEC",
  "Texas Longhorns": "SEC",
  "Texas": "SEC",

  // ACC
  "Boston College Eagles": "ACC",
  "Boston College": "ACC",
  "Clemson Tigers": "ACC",
  "Clemson": "ACC",
  "Duke Blue Devils": "ACC",
  "Duke": "ACC",
  "Florida State Seminoles": "ACC",
  "Florida State": "ACC",
  "Georgia Tech Yellow Jackets": "ACC",
  "Georgia Tech": "ACC",
  "Louisville Cardinals": "ACC",
  "Louisville": "ACC",
  "Miami Hurricanes": "ACC",
  "Miami (FL)": "ACC",
  "Miami": "ACC",
  "North Carolina Tar Heels": "ACC",
  "North Carolina": "ACC",
  "NC State Wolfpack": "ACC",
  "NC State": "ACC",
  "Notre Dame Fighting Irish": "ACC",
  "Notre Dame": "ACC",
  "Pittsburgh Panthers": "ACC",
  "Pittsburgh": "ACC",
  "Syracuse Orange": "ACC",
  "Syracuse": "ACC",
  "Virginia Cavaliers": "ACC",
  "Virginia": "ACC",
  "Virginia Tech Hokies": "ACC",
  "Virginia Tech": "ACC",
  "Wake Forest Demon Deacons": "ACC",
  "Wake Forest": "ACC",
  "California Golden Bears": "ACC",
  "California": "ACC",
  "SMU Mustangs": "ACC",
  "SMU": "ACC",
  "Stanford Cardinal": "ACC",
  "Stanford": "ACC",

  // Big 12
  "Arizona Wildcats": "Big 12",
  "Arizona": "Big 12",
  "Arizona State Sun Devils": "Big 12",
  "Arizona State": "Big 12",
  "Baylor Bears": "Big 12",
  "Baylor": "Big 12",
  "BYU Cougars": "Big 12",
  "BYU": "Big 12",
  "Cincinnati Bearcats": "Big 12",
  "Cincinnati": "Big 12",
  "Colorado Buffaloes": "Big 12",
  "Colorado": "Big 12",
  "Houston Cougars": "Big 12",
  "Houston": "Big 12",
  "Iowa State Cyclones": "Big 12",
  "Iowa State": "Big 12",
  "Kansas Jayhawks": "Big 12",
  "Kansas": "Big 12",
  "Kansas State Wildcats": "Big 12",
  "Kansas State": "Big 12",
  "Oklahoma State Cowboys": "Big 12",
  "Oklahoma State": "Big 12",
  "TCU Horned Frogs": "Big 12",
  "TCU": "Big 12",
  "Texas Tech Red Raiders": "Big 12",
  "Texas Tech": "Big 12",
  "UCF Knights": "Big 12",
  "UCF": "Big 12",
  "Utah Utes": "Big 12",
  "Utah": "Big 12",
  "West Virginia Mountaineers": "Big 12",
  "West Virginia": "Big 12",
};

/**
 * Finds the conference for a given team name using a comprehensive map.
 * It performs a case-insensitive lookup.
 * @param teamName The name of the team from the API.
 * @returns The conference name as a string, or undefined if not found.
 */
export function getConference(teamName: string): string | undefined {
    // This simple lookup is fast. A more complex fuzzy match could be added later if needed.
    return ncaaConferenceMap[teamName];
}
